# Generated by Django 3.0.2 on 2020-02-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp', models.ImageField(blank=True, null=True, upload_to='fir/images')),
                ('name', models.CharField(max_length=200)),
                ('aadhar', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=7)),
            ],
        ),
    ]
